// <auto-generated />
namespace Aud3MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SettingNullableColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SettingNullableColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201804111916209_SettingNullableColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
